# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
#
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
import time # This program takes about 2 seconds to run on my Lenovo Thinkpad -- Matthew Bruno 1/3/2021
from math import sqrt

start = time.time()

pentagonals = []
differences = []

def is_pent(x):
	f = (.5 + sqrt(.25+6*x))/3
	if f == int(f):
		return True
	else:
		return False

for n in range(1, 2500):
    pentagonals.append(int((3 * n * n - n) / 2))

for i in pentagonals:
    for k in pentagonals:
        if k < i:
            if is_pent(abs(i-k)):
                if is_pent(i+k):
                    differences.append(abs(i - k))
                else:
                    continue
            else:
                continue

answer = min(differences)
print(answer)

stop = time.time()
print("Time: ", stop - start)